name: Monthly Aldi Scrape

on:
  schedule:
    - cron: '0 3 16 * *'  # 3:00 AM UTC on the 16th = 11 PM ET (EDT) or 10 PM ET (EST)
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run the scrape script
        run: python aldi-test.py  # Updated to your file name

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add aldi_products.csv
          git diff-index --quiet HEAD || (git commit -m "Update Aldi scrape data for $(date +'%Y-%m-%d')" --allow-empty)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
